### ISSUE TITLE
Import the project to Android builder fails due printio-android library reference

### ISSUE THREAD

**Issue by Joohae** [printdotio/printio-android-example#1]
I'm trying to import the example code to android builder, but it's not able to import at all due printio-android library reference module.

The error that I received is:
- Project PIOSDKPOConcept:/Users/me/printio-android-example/PIOSDKPOConcept/project.properties:
  Library reference ../../printio-android could not be found
  Path is /Users/me/printio-android-example/PIOSDKPOConcept/../../printio-android which resolves to /Users/me/printio-android

Would you advise me to solve the problem?

**Comment by vladopajic** [comment]
Hey Joohae,

You need to add reference to the [Print.io SDK](https://github.com/printdotio/printio-android-sdk) project. Print.io Example (PIOSDKPOConcept) project is example app which uses Print.io SDK and it does not comes with Print.io SDK. 

This [project setup guide](https://github.com/printdotio/printio-android-sdk/blob/master/docs/PROJECT_SETUP.md) might help you with setup.

Regards,
Vlado
